### PR TITLE
Ryanyae 231 moving hero section

### PR DESCRIPTION
**Pull request by ryanyae**
## Description

Moved hero section of ProjectV2Join to be the new hero section of getInvolved.

## Updates

I have some concerns tho:
- How should we be repurposing the "Application Instruction" button? 
image
- It currently redirects the user to the GetInvolved page
- Secondly, I think we should think about making the sidebar un-collapsable, the new ProjectPages have an un-collapsable sidebar and I believe making this feature universal maybe for the better.

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by ryanyae** [comment]
[New GetInvolved hero section](https://trello.com/c/VGFzBD8T/231-new-getinvolved-hero-section)

**Comment by ElisaHu1** [comment]
i agree with you, the current implementation looks good
image
just one thing, i do not think they are very cohesive, can we remove the image on the right side and center the words and aligh it with the remaining pages

**Comment by ElisaHu1** [comment]
we do not need application button anymore

**Comment by ryanyae** [comment]
> i agree with you, the current implementation looks good image just one thing, i do not think they are very cohesive, can we remove the image on the right side and center the words and aligh it with the remaining pages

I didn't give too much into taking out the image entirely. I think its a really aesthetic image that, maybe, we could try and keep for the website? I think it brings a little bit of a more welcoming and pleasurable atmosphere to the page.

**Comment by ElisaHu1** [comment]
looks great, can you move the solid line from the above to between participants and lab member? https://us02web.zoom.us/j/9528215487?pwd=c1ZKQVNnSWdlM1RpdGxZWGN6UlBxZz09

**Comment by ryanyae** [comment]
> looks great, can you move the solid line from the above to between participants and lab member? https://us02web.zoom.us/j/9528215487?pwd=c1ZKQVNnSWdlM1RpdGxZWGN6UlBxZz09

Sorry, it seems that you pasted a zoom link.

**Comment by ElisaHu1** [comment]
> > looks great, can you move the solid line from the above to between participants and lab member? https://us02web.zoom.us/j/9528215487?pwd=c1ZKQVNnSWdlM1RpdGxZWGN6UlBxZz09
> 
> Sorry, it seems that you pasted a zoom link.

**Comment by ElisaHu1** [comment]
oh my bad, should be this
image

**Comment by ryanyae** [comment]
@ElisaHu1 I think taking out the line, completely, is better. What do you think this most recent commit is not going to have the line.

**Comment by ElisaHu1** [comment]
image
adding the line is to make the consistency through the page

**Comment by ryanyae** [comment]
@ElisaHu1 Fixed! What do you think moving this component that was at the bottom of the page to the top? 
image

**Comment by ElisaHu1** [comment]
> @ElisaHu1 Fixed! What do you think moving this component that was at the bottom of the page to the top? image

no opposition!

**Review by ElisaHu1 — APPROVED** [review]

**Pull request merged**
