### PR TITLE
add ncis desc and join us

### PR DESCRIPTION
**Pull request by erickj04**
## Description
- add NCIS description and join us information

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by ElisaHu1** [comment]
hi eric, we do not need tea& alumni page for ncis, also for the description page, we only need the first part

**Review by ryanyae — APPROVED** [review]
Looks good to me, just Address Elisa's change. Thank you for your hard work!

**Comment by erickj04** [comment]
so just delete the team&alumni page or can I just make it empty?

**Comment by ElisaHu1** [comment]
> so just delete the team&alumni page or can I just make it empty?

remove team& alumni page for NCIS

**Comment by ElisaHu1** [comment]
change: for project descirption page, only leaving project description
remove Get Involve page and the corresponding sidebar

**Comment by ElisaHu1** [comment]
compilation error bro 
image

**Comment by erickj04** [comment]
> compilation error bro image

**Comment by ryanyae** [comment]
@ElisaHu1 Do you want no sidebar for this project?

**Comment by ElisaHu1** [comment]
> @ElisaHu1 Do you want no sidebar for this project?
we still have sidebar, just not join our team page
image

**Review by ElisaHu1 — APPROVED** [review]
good to me, thanks erick

**Pull request merged**
