### PR TITLE
Jingxuan timeline edit

### PR DESCRIPTION
**Pull request by Taosit**
## Description

Edit timeline entry page (with implementation of the functionalities)
screen_cast

Note: A few changes need to be made to the backend in order for it to work. Once those changes are made, please launch the server, log in with an account that has admin permission, and go to (for example) http://localhost:3000/timeline/6064076dd3b059682153bceb/edit.

Issues and todos:
- Client-side validation for author name and contributors needs to be made. It will require a redux slice for users. There also needs to be somewhere in the UI to display error messages.
- Success message is also missing. Since the user will already be navigated to the timeline page by that time, there needs to be a popup to let the user know their edit got through. (I was going to make a popup component, then I realized there was already one, but I couldn't find a way to use it.)
- Potential error message from the server isn't displayed. However, it's not really an issue. Once name validation is added, there'll be no way to send an invalid request to the server from the browser.
- The design needs to be finalized and coordinated with the add timeline page.
- There should be an error page if the timeline id in the url doesn't exist in the database.

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by Taosit** [comment]
[Edit timeline entry](https://trello.com/c/V1eN4cFM/80-edit-timeline-entry)

**Comment by ElisaHu1** [comment]
image

it is giving me compile error for the edit text file

**Comment by ElisaHu1** [comment]
image
the select date is not working. also you miss the project implementation?

**Review by ElisaHu1 — APPROVED** [review]
I tested both mobile and browser, no bug found

**Pull request merged**
