### PR TITLE
Work on Get Involved Page

### PR DESCRIPTION
**Pull request by svolterra**
## Description

This PR:
- Deletes the sentence component of project Q&A sections
- Modifies the GetInvolvedSidebar to have a more consistent style with the ProjectNavbar in terms of opening and closing buttons.
- Renames Tech Support to Coding Team
- Adds drop-downs for application instructions instead of navigating user to old website
- Links each role to its relevant section

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by svolterra** [comment]
[get involve](https://trello.com/c/oeq3AHbs/154-get-involve)

**Comment by svolterra** [comment]
[delete the sentence component](https://trello.com/c/gWeF3AaZ/157-delete-the-sentence-component)

**Comment by ElisaHu1** [comment]
everything looks great! Also i love the QA for the 402 project you have here! just one minor thing, what is this application instruction would lead to? do we still need this button?
image

**Comment by svolterra** [comment]
@ElisaHu1 Oh great catch! I don't think we need that anymore. Will be removing it now :)

**Comment by ryanyae** [comment]
image
There is just a small gap the very top of the sidebar for the Get Involved page.

**Comment by ryanyae** [comment]
@ElisaHu1 what do you think of adding a hover style for the drop down menu, being that the cursor changes to a pointer?
image

**Review by ryanyae — CHANGES_REQUESTED** [review]
Besides the comment that I raised earlier about the GetInvolved sidebar, I guess we will just wait to discuss your guys' opinion on the hover effect. Other than those thank you for your hard work!

**Comment by svolterra** [comment]
Addressed code review comments @ryanyae @ElisaHu1 😄 Tysm for the feedback!

**Review by ElisaHu1 — APPROVED** [review]
looks great!

**Review by ryanyae — APPROVED** [review]
Looks good to me as well! Thank you for your hard work!

**Pull request merged**
