### PR TITLE
Added coding team logo, blurb + Removed gallery from coding team page

### PR DESCRIPTION
**Pull request by j-asmin3**
## Description

1. Added Coding Team Logo to Home page
2. Added Coding Team members' names, titles and blurbs to People page
3. Removed gallery from Coding Team page

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [x] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Review by ElisaHu1 — APPROVED** [review]
Love it! Great work Jasmine!

**Review by ryanyae — CHANGES_REQUESTED** [review]
Thinking from a design perspective, it may be best to map the images onto a grid, this would mean that you would also need to change how the mobile functionality works. We could either make the individual images smaller or the grid idea that I had just mentioned. What do you think Elisa?

**Comment by ElisaHu1** [comment]
> Thinking from a design perspective, it may be best to map the images onto a grid, this would mean that you would also need to change how the mobile functionality works. We could either make the individual images smaller or the grid idea that I had just mentioned. What do you think Elisa? Screenshot 2023-11-09 at 11 26 28 AM

i am not sure what do you mean? you want to map image to what grid? Mobile view for the home page looks fine for me>

**Comment by ryanyae** [comment]
> > Thinking from a design perspective, it may be best to map the images onto a grid, this would mean that you would also need to change how the mobile functionality works. We could either make the individual images smaller or the grid idea that I had just mentioned. What do you think Elisa? Screenshot 2023-11-09 at 11 26 28 AM
> 
> i am not sure what do you mean? you want to map image to what grid? Mobile view for the home page looks fine for me>

Making a grid of the projects so that its evenly distributed across the entire page instead of having the coding in its own row.

**Comment by ElisaHu1** [comment]
> > > Thinking from a design perspective, it may be best to map the images onto a grid, this would mean that you would also need to change how the mobile functionality works. We could either make the individual images smaller or the grid idea that I had just mentioned. What do you think Elisa? Screenshot 2023-11-09 at 11 26 28 AM
> > 
> > 
> > i am not sure what do you mean? you want to map image to what grid? Mobile view for the home page looks fine for me>
> 
> Making a grid of the projects so that its evenly distributed across the entire page instead of having the coding in its own row.

I have no preference, if it is a simple change yeah sure we can do that, but i think jasmine is on vacation this week. It make sense to merge it in now and we can address this later if necessary.

**Review by ryanyae — APPROVED** [review]

**Comment by ryanyae** [comment]
> > > > Thinking from a design perspective, it may be best to map the images onto a grid, this would mean that you would also need to change how the mobile functionality works. We could either make the individual images smaller or the grid idea that I had just mentioned. What do you think Elisa? Screenshot 2023-11-09 at 11 26 28 AM
> > > 
> > > 
> > > i am not sure what do you mean? you want to map image to what grid? Mobile view for the home page looks fine for me>
> > 
> > 
> > Making a grid of the projects so that its evenly distributed across the entire page instead of having the coding in its own row.
> 
> I have no preference, if it is a simple change yeah sure we can do that, but i think jasmine is on vacation this week. It make sense to merge it in now and we can address this later if necessary.

Sounds good to me.

**Pull request merged**
