### PR TITLE
mobile view footer bug

### PR DESCRIPTION
**Pull request by erickj04**
## Description

- change footer.css 

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by ryanyae** [comment]
@erickj04 Do you think you could make the navigate and project divs display flex, so that those 2 divs are side by side?

**Comment by ryanyae** [comment]
And do you think you could fix this? 
image

**Comment by ryanyae** [comment]
Idk if you saw the change that I had requested earlier, after you address that I think I am able to merge this ticket into main

**Comment by erickj04** [comment]
image
Sorry isn't this the problem?

**Review by ryanyae — APPROVED** [review]
Looks good to me! Thank you Erik for your hard work!

**Comment by ryanyae** [comment]
@erickj04 Now just resolve the merge conflicts

**Review by ryanyae — DISMISSED** [review]
Just resolve the merge conflicts now. Thank you Erik for your hard work!

**Review by ElisaHu1 — APPROVED** [review]
awesome work Erick! Keep moving!

**Pull request merged**
