### PR TITLE
increased the size of the font and changed the title to visual cognit…

### PR DESCRIPTION
**Pull request by OttoChen312**
…ion lab

## Description

Changed the font size and title for home page

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by OttoChen312** [comment]
[ui change](https://trello.com/c/8NUotddG/223-ui-change)

**Review by ElisaHu1 — APPROVED** [review]

**Comment by ElisaHu1** [comment]
@ryanyae

**Review by ryanyae — CHANGES_REQUESTED** [review]
Great work! I would just like to ask for one thing and its changing these icon and text divs to be centered with each other. 
image

**Review by ryanyae — APPROVED** [review]
Looks good to me! Thank you Otto!

**Pull request merged**
