### PR TITLE
Added the timeline pagination component

### PR DESCRIPTION
**Pull request by MuzammilC**
## Description

This PR entails the development of the timeline pagination component.

## Updates

The number of records that are shown per page has to be decided. But other than that, the development of the pagination component is complete.

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Review by ryanyae — DISMISSED** [review]
Good job Muz, I just want to see you add more items to the db and increasing the pagination number before approving. The code is very intuitive and will most definitely work but getting practice with working with the db is always good practice.

**Comment by ryanyae** [comment]
Also the pagination div is not centered, 
image

**Comment by ryanyae** [comment]
[investigation: add new timeline entry and edit timeline entry broken](https://trello.com/c/Uy3FerY3/216-investigation-add-new-timeline-entry-and-edit-timeline-entry-broken)

**Comment by MuzammilC** [comment]
Thanks, Ryan for the comments. In my new commits I have centered the div, added more records per page, and tested it with the backend. I also added scroll to top when the page is changed using pagination.

**Comment by ElisaHu1** [comment]
Starting the development server...
Failed to compile.

/Users/elisahu/VCL/VCL-content-platform/src/pages/Timeline/Timeline.tsx
TypeScript error in /Users/elisahu/VCL/VCL-content-platform/src/pages/Timeline/Timeline.tsx(243,18):
Property '_id' is missing in type '{ author: string; title: string; project: string; date: Date; descriptions: string[]; contributors: string[]; hyperlinks: string[]; updatedTime: string; categories: string[]; isLoggedIn: boolean; onClickDelete: () => void; }' but required in type 'TimelineCommitBlockProps'.  TS2741

    241 |                   <li key={i}>
    242 |                 <span className={"timeline-container-span-" + prj}></span>
  > 243 |                 <TimelineCommitBlock
        |                  ^
    244 |                   author={commit.author}
    245 |                   title={commit.title}
    246 |                   project={commit.project}

**Comment by MuzammilC** [comment]
It should be fixed now

**Review by ElisaHu1 — APPROVED** [review]

**Pull request merged**
