### PR TITLE
Nav fix

### PR DESCRIPTION
**Pull request by Taosit**
## Description

Fixed some issues with the navbar, including:
 - alignment on mobile
 - uneven spacing on desktop
 - overflowing on tablet
 
It is responsive from 760px onward. (The smallest ipad is 768px wide, so it works on all devices). However, the text "Get Involved" is wrapping from 700px to 760px. I think shrinking the font size even more can impact readability. Therefore, the easiest way to solve this is to use the mobile component for screens up to 760px wide.

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by ElisaHu1** [comment]
how come I click any project page, then about page then any other page in nav bar in order, there will be a clear right shift for nav bar

**Review by svolterra — COMMENTED** [review]
Looks good to me once the nav bar shift is fixed when switching pages (re: [Elisa's comment](https://github.com/UBC-VCL/VCL-content-platform/pull/50#issuecomment-1355747465)) as it still shifts for me at the moment.

**Comment by Taosit** [comment]
Hi Sara! Happy new year!
I messaged Elisa about the shift but I should have said something in this thread as well.
So the shift is caused by the scroll bar which appears on completed pages but disappears on pages that aren't yet scrollable (i.e. pages that are not yet complete). Once we add more content to those pages, the scroll bar will show up and the problem will go away.
If this is what you were talking about, I don't think any fix is necessary at this stage. If there are more issues beside the scrollbar, can you provide more details about the issues?

**Review by ElisaHu1 — APPROVED** [review]
Looks good to me, thanks Jingxuan : )

**Pull request merged**
