### PR TITLE
Connorwon 206 resource to navbar

### PR DESCRIPTION
**Pull request by ConnorWon**
## Description

Adding Resources link to navbar and adding down arrow to nav links with dropdown

## Updates

- updated class names for dropdown menu to be more general
- added new constants for Resources dropdown
- moved resources route in routes.ts to baseRoutes

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by ConnorWon** [comment]
[add resource in navigation bar](https://trello.com/c/0PwD2HcT/206-add-resource-in-navigation-bar)

**Comment by ElisaHu1** [comment]
Hi conner! can you fix the merge conflict?

**Comment by ConnorWon** [comment]
> Hi conner! can you fix the merge conflict?

Done

**Comment by ryanyae** [comment]
@ConnorWon Would it be possible to also make the arrow blue when the resource is blue? 
image

**Comment by ryanyae** [comment]
@ConnorWon There is a static file with all the information that we need to display these pages, maybe you could use that static file aswell to "dynamically" display the available resources that we have. As you can see the items that are in the overview do not match with the items that we have in your version of the resource drop down.
image

**Review by ryanyae — CHANGES_REQUESTED** [review]
Apart from the changes that I requested it looks good!

**Comment by ConnorWon** [comment]
> @ConnorWon Would it be possible to also make the arrow blue when the resource is blue? The resource tab is blue when you are in the resource overview page, same goes for the Project tab.
> 
> image

Done

**Comment by ConnorWon** [comment]
> @ConnorWon There is a static file with all the information that we need to display these pages, maybe you could use that static file aswell to "dynamically" display the available resources that we have. As you can see the items that are in the overview do not match with the items that we have in your version of the resource drop down. image

Done. To do this though, I changed Resource property "title" to "name" to better fit with what is used in the map part of the linksWithMenu component. Made the appropriate changes in the codebase to match with this change.
Screenshot 2024-01-27 at 10 14 04 PM

**Review by ElisaHu1 — APPROVED** [review]
Looks good to me! thanks Connor

**Comment by ryanyae** [comment]
@ConnorWon One last styling thing I wanted to point out was that when you hover "All Resources" within the dropmenu, the transformation will actually resize the dropmenu's container, this effect should be consistent with the project dropmenu where there is no resizing for the actual container but transformations of the text is still there.

**Comment by ConnorWon** [comment]
> @ConnorWon One last styling thing I wanted to point out was that when you hover "All Resources" within the dropmenu, the transformation will actually resize the dropmenu's container, this effect should be consistent with the project dropmenu where there is no resizing for the actual container but transformations of the text is still there.

The project dropdown menu actually does resize the container if the anchor element holding the text is large enough width-wise. For example if you hover over "Image Transitions" in the project dropdown, it will also cause the container to transform. So, would you want me to make it so the container never transforms or just leave it how it is?

**Comment by ryanyae** [comment]
> > @ConnorWon One last styling thing I wanted to point out was that when you hover "All Resources" within the dropmenu, the transformation will actually resize the dropmenu's container, this effect should be consistent with the project dropmenu where there is no resizing for the actual container but transformations of the text is still there.
> 
> The project dropdown menu actually does resize the container if the anchor element holding the text is large enough width-wise. For example if you hover over "Image Transitions" in the project dropdown, it will also cause the container to transform. So, would you want me to make it so the container never transforms or just leave it how it is?

I see, in my personal opinion I would want the container to never transform but the other titles to. @ElisaHu1 what do you think?

**Comment by ElisaHu1** [comment]
i think this issue exist before the pr as well, it would be nice if @ConnorWon can fix it. But if it is time costing, we can put it aside

**Comment by ConnorWon** [comment]
I fixed the issue, making it so the dropdown menu does not resize at all when hovering the menu items. I did it by adding an onTransitionEnd event listener to the menu, which pretty much on initially opening the menu will dynamically determine the width of the dropdown and set the container to that width.

There is one small bug though. While the dropdown is still opening if you hover text within the dropdown that would without my fix cause the container to resize (ex. "All Resources"), then the container will take on that resized width.


https://github.com/UBC-VCL/VCL-content-platform/assets/120760211/03de4b92-41da-4289-a4a0-5fa013e41964


Don't know if you can see it, but in the console it shows that the container was larger when I hovered over "Image Transitions" before the menu opened fully.


As you can see the bug is quite difficult to produce. Any thoughts?

**Comment by ConnorWon** [comment]
> I fixed the issue, making it so the dropdown menu does not resize at all when hovering the menu items. I did it by adding an onTransitionEnd event listener to the menu, which pretty much on initially opening the menu will dynamically determine the width of the dropdown and set the container to that width.
> 
> There is one small bug though. While the dropdown is still opening if you hover text within the dropdown that would without my fix cause the container to resize (ex. "All Resources"), then the container will take on that resized width.
> 
>  Screen.Recording.2024-02-02.at.1.22.10.AM.mov 
> Don't know if you can see it, but in the console it shows that the container was larger when I hovered over "Image Transitions" before the menu opened fully.
> 
> As you can see the bug is quite difficult to produce. Any thoughts?

Have workaround for bug

**Pull request merged**
