### PR TITLE
Modify the team&alumni page

### PR DESCRIPTION
**Pull request by kaiqianyyang**
## Description

remove add member button, delete modify icon and delete icon

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by kaiqianyyang** [comment]
[Modify the team&alumni page](https://trello.com/c/6kjytrRL/83-modify-the-teamalumni-page)

**Comment by kaiqianyyang** [comment]
[Modify the team&alumni page](https://trello.com/c/6kjytrRL/83-modify-the-teamalumni-page)

**Comment by ElisaHu1** [comment]
I cannot npm start your branch QAQ 
image

**Comment by ElisaHu1** [comment]
do we have a way to bypass it? since other PR works without commenting the eslint.

**Comment by ElisaHu1** [comment]
also did you comment out the whole yml file? What exactly you have commented out?

**Comment by kaiqianyyang** [comment]
> do we have a way to bypass it? since other PR works without commenting the eslint.

I haven't found one so far, I connected with @svolterra last Friday but the error is still outstanding...

**Comment by kaiqianyyang** [comment]
> also did you comment out the whole yml file? What exactly you have commented out?

I commented line#17 in yml file

**Review by svolterra — APPROVED** [review]
LGTM! :) Thank you for the great work 🥳 🏆

**Pull request merged**
