### PR TITLE
Add Coding Team to Projects and People Pages

### PR DESCRIPTION
**Pull request by svolterra**
## Description

Get started on adding the coding team to project and people pages

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by svolterra** [comment]
[project page for coding team and update people page](https://trello.com/c/lisnr3Qb/171-project-page-for-coding-team-and-update-people-page)

**Comment by ElisaHu1** [comment]
@svolterra can you fix the conflict files?

**Review by ElisaHu1 — APPROVED** [review]
looks great Sarah!

**Review by ryanyae — APPROVED** [review]
Looks good to me as well! Thank you for your work!

**Pull request merged**
