### PR TITLE
Imported Project Info

### PR DESCRIPTION
**Pull request by kumarpit**
## Description

Imported project info (description, images, links) for NOVA, Correlation, Image Transitions, and IDEO. View at `{localhost}/projects/{name}`

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [x] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by kumarpit** [comment]
[Populate the projects page with descriptions and information from each team](https://trello.com/c/KSFyHASH/75-populate-the-projects-page-with-descriptions-and-information-from-each-team)

**Comment by ElisaHu1** [comment]
this looks great! I will wait for your other pr to merge in!

**Review by svolterra — APPROVED** [review]
It seems to me that the Perceptual Modes project was missed in this PR! Otherwise good work thank you for your effort on this!

**Comment by ElisaHu1** [comment]
Hi Arpit I will create another ticket for the misalignment between the main project page and the project sidebar. But we can merge in this first. Thanks for your work!

**Pull request merged**
