### PR TITLE
Connorwon 222 member alumni separation

### PR DESCRIPTION
**Pull request by ConnorWon**
## Description

Frontend portion of alumni vs non-alumni separation

## Changes

* Added alumni section to project team and people page
* Updated filter method on people page to account for this
* Added backend call to populate project team page, instead of static data
* Updated add member form to include all fields of member model

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by ConnorWon** [comment]
[project members vs alumni separation](https://trello.com/c/KxCNxlPq/222-project-members-vs-alumni-separation)

**Comment by ConnorWon** [comment]
[Changing People Page API call](https://trello.com/c/nxdImpnc/228-changing-people-page-api-call)

**Review by ryanyae — CHANGES_REQUESTED** [review]
Just address the conflicts and address my comments regarding to the BE ticket and we can merge this in.

**Comment by ConnorWon** [comment]
> nice ui, i wonder what did you do to test this? also can you solve the conflicting files

I added some dummy data like Ryan suggested in the backend ticket and viewed the project and people pages to ensure they look as expected. Attached the videos that show the pages with the dummy data included


https://github.com/UBC-VCL/VCL-content-platform/assets/120760211/d46113bd-ab17-4e8f-8f04-341a4b621c66


https://github.com/UBC-VCL/VCL-content-platform/assets/120760211/3a365027-3544-4329-8b38-54a2bd61cb9f

**Review by ElisaHu1 — APPROVED** [review]

**Comment by ConnorWon** [comment]
Removed the breadcrumbs and added the max-width as mentioned in https://github.com/UBC-VCL/VCL-content-platform-server/pull/43#pullrequestreview-1955800067

**Review by ryanyae — APPROVED** [review]

**Pull request merged**
