### PR TITLE
Project team mobile

### PR DESCRIPTION
**Pull request by j-asmin3**
## Description

Project team mobile view:
1. Heading (team name) + member info blocks (name, position, blurb)
2. Left some legacy backend requests that can be
altered to display the correct project. Currently
displaying management team by default.

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by j-asmin3** [comment]
[Mobile-view of ProjectTeam](https://trello.com/c/Lo6T95AJ/205-mobile-view-of-projectteam)

**Comment by ElisaHu1** [comment]
hi jasmine! can you fix the merge conflict?

**Review by ryanyae — CHANGES_REQUESTED** [review]
@j-asmin3 How did you test this?

**Comment by ryanyae** [comment]
The build will not compile

**Comment by ryanyae** [comment]
This code is still not compiling, 
image

**Comment by ryanyae** [comment]
@j-asmin3 is this ticket finished? 
image

**Review by ryanyae — CHANGES_REQUESTED** [review]
Looks really good, if you could add the profile icon to each member and take out the contact section that would be great! Otherwise great job!

**Comment by ryanyae** [comment]
I will have to close this PR as we've decided on going with someone else's implementation. This is abrupt and hope that you understand. Nonetheless thank you for your work, Jasmine.

**Pull request closed without merging**
