### PR TITLE
Update People.tsx

### PR DESCRIPTION
**Pull request by ryanyae**
## Description

Created a custom ordering function for ordering the People page in a specific position orientated fashion.
## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by ElisaHu1** [comment]
image
what happen to the backend? I remember it was working last week? I run this with local backend master

**Comment by ElisaHu1** [comment]
i think somehow this get reverted to 4000? 
image

**Comment by ryanyae** [comment]
> i think somehow this get reverted to 4000? image

Is this still an issue?

**Review by ElisaHu1 — APPROVED** [review]

**Comment by ryanyae** [comment]
[re ordering lab position in people and teams](https://trello.com/c/hMtj00MH/212-re-ordering-lab-position-in-people-and-teams)

**Pull request merged**
