### PR TITLE
Dynamic Navbar

### PR DESCRIPTION
**Pull request by Keshraf**
## Description

From 540~700 width, the HomePage Title is hidden and on different resolutions the title will be covered completely (more on the tablet resolutions). 

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by Keshraf** [comment]
[Dynamic Navbar](https://trello.com/c/ph82vmZq/199-dynamic-navbar)

**Review by ryanyae — DISMISSED** [review]
I believe that the issue is still present in some resolutions.

**Comment by ryanyae** [comment]
@ElisaHu1 This ticket should be done!

**Review by ElisaHu1 — APPROVED** [review]
thank you ryan for taking this up!

**Pull request merged**
