### PR TITLE
Adjust sidebar menu icon positionm, stick navbar to the top, adjust the design of each project page

### PR DESCRIPTION
**Pull request by kaiqianyyang**
## Description

This pr is ticket **#86 Project Overhaul: Correlation** and part of the ticket **#87 Project sidebar change**.

- Adjust sidebar menu icon to be on the left top side of the page (under navbar)
- Stick navbar to the top
- Adjust the design of each project page
- Store style in Project.css file

Screen Shot 2022-12-16 at 10 59 43 PM

Screen Shot 2022-12-16 at 11 00 33 PM

Screen Shot 2022-12-16 at 11 01 04 PM

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

### CODE REVIEW

**Comment by kaiqianyyang** [comment]
[Project Overhaul: Correlation](https://trello.com/c/KLGBKFup/86-project-overhaul-correlation)

**Comment by ElisaHu1** [comment]
hi cathy! thanks so much for your pr! this looks awesome 2 things i forgot to mention in the ticket (my bad!) 
1. the sidebar should by default open when we go into a project page, so it is obvious for user to find different tab navigation.
2. the sidebar should not overlap with the nav bar, so we want it always below the nav bar and above the footer
image

**Comment by kaiqianyyang** [comment]
> hi cathy! thanks so much for your pr! this looks awesome 2 things i forgot to mention in the ticket (my bad!)
> 
> 1. the sidebar should by default open when we go into a project page, so it is obvious for user to find different tab navigation.
> 2. the sidebar should not overlap with the nav bar, so we want it always below the nav bar and above the footer
> 
> image

Hi @ElisaHu1, thank you for the info. But these two things appear to be on **#87 Project sidebar change**. As I mentioned in the description above, I only worked on **#86 Project Overhaul: Correlation**

1. adjusting the design of each project page as they are currently pretty bare-bones in terms of style
2. create a CSS file to store the pattern

and part of #87

3. Adjust collapse icon to be on the left top side of the page (under navbar)
4. Stick navbar to the top

Honestly, I don’t really know how to make the sidebar not overlap the navigation bar and the footer without breaking other things… 

Since 3 and 4 were mentioned in last week's meeting as part of **#87 Project sidebar change** (but not written in the description on Trello board) and these are pretty relevant to the whole structure of ticket **#86 Project Overhaul: Correlation**. I just included these two changes in this PR, and once this change is approved, you can edit the description of **#87  Project sidebar change** with the expectations you want to have for Project sidebar :) .

**Comment by ElisaHu1** [comment]
my bad! i will update the info for the other ticket! but this pr looks great to me! @svolterra do you have any suggestions about the code?

**Review by ElisaHu1 — APPROVED** [review]

**Comment by kaiqianyyang** [comment]
[Project Overhaul: Correlation](https://trello.com/c/KLGBKFup/86-project-overhaul-correlation)

**Review by svolterra — APPROVED** [review]
Looks good to me! Thank you! 😄  @ElisaHu1 the points you mentioned in [your comment ](https://github.com/UBC-VCL/VCL-content-platform/pull/51#issuecomment-1360586011)were addressed in [this PR](https://github.com/UBC-VCL/VCL-content-platform/pull/53) by William (@wnguye03).

**Pull request merged**
